// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:gurukula_ai/data/models/activity_event.dart';
import 'package:gurukula_ai/data/models/enums.dart';
import 'package:gurukula_ai/data/models/flashcard.dart';
import 'package:gurukula_ai/data/models/idea.dart';
import 'package:gurukula_ai/data/models/quiz.dart';
import 'package:gurukula_ai/data/models/quiz_question.dart';
import 'package:gurukula_ai/data/models/quiz_result.dart';
import 'package:gurukula_ai/data/models/rewrite.dart';
import 'package:gurukula_ai/data/models/study_document.dart';
import 'package:gurukula_ai/data/models/summary.dart';
import 'package:gurukula_ai/data/models/user_profile.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ActivityEventAdapter());
    registerAdapter(ActivityTypeAdapter());
    registerAdapter(DifficultyAdapter());
    registerAdapter(DocumentTypeAdapter());
    registerAdapter(FlashcardAdapter());
    registerAdapter(IdeaAdapter());
    registerAdapter(QuestionTypeAdapter());
    registerAdapter(QuizAdapter());
    registerAdapter(QuizQuestionAdapter());
    registerAdapter(QuizResultAdapter());
    registerAdapter(RewriteAdapter());
    registerAdapter(RewriteToneAdapter());
    registerAdapter(StudyDocumentAdapter());
    registerAdapter(SummaryAdapter());
    registerAdapter(UserProfileAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ActivityEventAdapter());
    registerAdapter(ActivityTypeAdapter());
    registerAdapter(DifficultyAdapter());
    registerAdapter(DocumentTypeAdapter());
    registerAdapter(FlashcardAdapter());
    registerAdapter(IdeaAdapter());
    registerAdapter(QuestionTypeAdapter());
    registerAdapter(QuizAdapter());
    registerAdapter(QuizQuestionAdapter());
    registerAdapter(QuizResultAdapter());
    registerAdapter(RewriteAdapter());
    registerAdapter(RewriteToneAdapter());
    registerAdapter(StudyDocumentAdapter());
    registerAdapter(SummaryAdapter());
    registerAdapter(UserProfileAdapter());
  }
}
